export const ValidationErrorCodes = {
  // Allocation errors
  ALLOCATION_SUM_INVALID: "ALLOCATION_SUM_INVALID",
  ALLOCATION_EXCEEDS_BALANCE: "ALLOCATION_EXCEEDS_BALANCE",
  ALLOCATION_NEGATIVE_AMOUNT: "ALLOCATION_NEGATIVE_AMOUNT",
  ALLOCATION_DUPLICATE_POOL: "ALLOCATION_DUPLICATE_POOL",
  ALLOCATION_POOL_NOT_FOUND: "ALLOCATION_POOL_NOT_FOUND",
  ALLOCATION_EMPTY: "ALLOCATION_EMPTY",

  // Transaction errors
  TRANSACTION_AMOUNT_INVALID: "TRANSACTION_AMOUNT_INVALID",
  TRANSACTION_DATE_INVALID: "TRANSACTION_DATE_INVALID",
  TRANSACTION_CHANNEL_NOT_FOUND: "TRANSACTION_CHANNEL_NOT_FOUND",
  TRANSACTION_POOL_NOT_FOUND: "TRANSACTION_POOL_NOT_FOUND",
  TRANSACTION_ALLOCATION_MISMATCH: "TRANSACTION_ALLOCATION_MISMATCH",
  TRANSACTION_DESCRIPTION_EMPTY: "TRANSACTION_DESCRIPTION_EMPTY",

  // Credit payment errors
  CREDIT_PAYMENT_EXCEEDS_DEBT: "CREDIT_PAYMENT_EXCEEDS_DEBT",
  CREDIT_PAYMENT_EXCEEDS_POOL_BALANCE: "CREDIT_PAYMENT_EXCEEDS_POOL_BALANCE",
  CREDIT_PAYMENT_INVALID_SOURCE: "CREDIT_PAYMENT_INVALID_SOURCE",
  CREDIT_PAYMENT_INVALID_DESTINATION: "CREDIT_PAYMENT_INVALID_DESTINATION",
  CREDIT_PAYMENT_CROSS_POOL_VIOLATION: "CREDIT_PAYMENT_CROSS_POOL_VIOLATION",

  // Balance errors
  BALANCE_NEGATIVE: "BALANCE_NEGATIVE",
  BALANCE_INCONSISTENT: "BALANCE_INCONSISTENT",
  BALANCE_CALCULATION_ERROR: "BALANCE_CALCULATION_ERROR",

  // Data integrity errors
  DATA_INTEGRITY_ORPHANED_REFERENCE: "DATA_INTEGRITY_ORPHANED_REFERENCE",
  DATA_INTEGRITY_CIRCULAR_REFERENCE: "DATA_INTEGRITY_CIRCULAR_REFERENCE",
  DATA_INTEGRITY_INVALID_STATE: "DATA_INTEGRITY_INVALID_STATE",

  // Schema validation errors
  SCHEMA_VALIDATION_FAILED: "SCHEMA_VALIDATION_FAILED",
  REQUIRED_FIELD_MISSING: "REQUIRED_FIELD_MISSING",
  INVALID_FORMAT: "INVALID_FORMAT",

  // Import errors
  IMPORT_INVALID_DATE: "IMPORT_INVALID_DATE",
  IMPORT_INVALID_AMOUNT: "IMPORT_INVALID_AMOUNT",
  IMPORT_MISSING_REQUIRED_FIELD: "IMPORT_MISSING_REQUIRED_FIELD",
  IMPORT_CATEGORY_NOT_FOUND: "IMPORT_CATEGORY_NOT_FOUND",
  IMPORT_CHANNEL_NOT_FOUND: "IMPORT_CHANNEL_NOT_FOUND",
  IMPORT_POOL_NOT_FOUND: "IMPORT_POOL_NOT_FOUND",

  // General field validation errors
  FIELD_REQUIRED: "FIELD_REQUIRED",
  FIELD_TOO_SHORT: "FIELD_TOO_SHORT",
  FIELD_TOO_LONG: "FIELD_TOO_LONG",
  FIELD_INVALID_EMAIL: "FIELD_INVALID_EMAIL",
  FIELD_INVALID_URL: "FIELD_INVALID_URL",
  FIELD_INVALID_COLOR: "FIELD_INVALID_COLOR",
  FIELD_INVALID_CURRENCY: "FIELD_INVALID_CURRENCY",
  FIELD_INVALID_ENUM: "FIELD_INVALID_ENUM",
  FIELD_INVALID_NUMBER: "FIELD_INVALID_NUMBER",
  FIELD_NEGATIVE_NUMBER: "FIELD_NEGATIVE_NUMBER",
  FIELD_POSITIVE_NUMBER_REQUIRED: "FIELD_POSITIVE_NUMBER_REQUIRED",

  // Business logic validation errors
  GOAL_REQUIRES_TARGET: "GOAL_REQUIRES_TARGET",
  CREDIT_REQUIRES_LIMIT: "CREDIT_REQUIRES_LIMIT",
  CASH_NO_INSTITUTION: "CASH_NO_INSTITUTION",
  SUBCATEGORY_MISMATCH: "SUBCATEGORY_MISMATCH",
  SOURCE_DESTINATION_SAME: "SOURCE_DESTINATION_SAME",

  // User validation errors
  USER_ID_REQUIRED: "USER_ID_REQUIRED",
  DISPLAY_NAME_REQUIRED: "DISPLAY_NAME_REQUIRED",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_INVALID: "EMAIL_INVALID",

  // Budget validation errors
  BUDGET_ID_REQUIRED: "BUDGET_ID_REQUIRED",
  BUDGET_NAME_REQUIRED: "BUDGET_NAME_REQUIRED",
  OWNER_ID_REQUIRED: "OWNER_ID_REQUIRED",

  // Pool validation errors
  POOL_ID_REQUIRED: "POOL_ID_REQUIRED",
  POOL_NAME_REQUIRED: "POOL_NAME_REQUIRED",

  // Channel validation errors
  CHANNEL_ID_REQUIRED: "CHANNEL_ID_REQUIRED",
  CHANNEL_NAME_REQUIRED: "CHANNEL_NAME_REQUIRED",

  // Category validation errors
  CATEGORY_ID_REQUIRED: "CATEGORY_ID_REQUIRED",
  CATEGORY_NAME_REQUIRED: "CATEGORY_NAME_REQUIRED",
  SUBCATEGORY_ID_REQUIRED: "SUBCATEGORY_ID_REQUIRED",
  SUBCATEGORY_NAME_REQUIRED: "SUBCATEGORY_NAME_REQUIRED",
} as const;
