export const ValidationErrorCodes = {
  // Allocation errors
  ALLOCATION_SUM_INVALID: "ALLOCATION_SUM_INVALID",
  ALLOCATION_EXCEEDS_BALANCE: "ALLOCATION_EXCEEDS_BALANCE",
  ALLOCATION_NEGATIVE_AMOUNT: "ALLOCATION_NEGATIVE_AMOUNT",
  ALLOCATION_DUPLICATE_POOL: "ALLOCATION_DUPLICATE_POOL",
  ALLOCATION_POOL_NOT_FOUND: "ALLOCATION_POOL_NOT_FOUND",
  ALLOCATION_EMPTY: "ALLOCATION_EMPTY",

  // Transaction errors
  TRANSACTION_AMOUNT_INVALID: "TRANSACTION_AMOUNT_INVALID",
  TRANSACTION_DATE_INVALID: "TRANSACTION_DATE_INVALID",
  TRANSACTION_CHANNEL_NOT_FOUND: "TRANSACTION_CHANNEL_NOT_FOUND",
  TRANSACTION_POOL_NOT_FOUND: "TRANSACTION_POOL_NOT_FOUND",
  TRANSACTION_ALLOCATION_MISMATCH: "TRANSACTION_ALLOCATION_MISMATCH",
  TRANSACTION_DESCRIPTION_EMPTY: "TRANSACTION_DESCRIPTION_EMPTY",

  // Credit payment errors
  CREDIT_PAYMENT_EXCEEDS_DEBT: "CREDIT_PAYMENT_EXCEEDS_DEBT",
  CREDIT_PAYMENT_EXCEEDS_POOL_BALANCE: "CREDIT_PAYMENT_EXCEEDS_POOL_BALANCE",
  CREDIT_PAYMENT_INVALID_SOURCE: "CREDIT_PAYMENT_INVALID_SOURCE",
  CREDIT_PAYMENT_INVALID_DESTINATION: "CREDIT_PAYMENT_INVALID_DESTINATION",
  CREDIT_PAYMENT_CROSS_POOL_VIOLATION: "CREDIT_PAYMENT_CROSS_POOL_VIOLATION",

  // Balance errors
  BALANCE_NEGATIVE: "BALANCE_NEGATIVE",
  BALANCE_INCONSISTENT: "BALANCE_INCONSISTENT",
  BALANCE_CALCULATION_ERROR: "BALANCE_CALCULATION_ERROR",

  // Data integrity errors
  DATA_INTEGRITY_ORPHANED_REFERENCE: "DATA_INTEGRITY_ORPHANED_REFERENCE",
  DATA_INTEGRITY_CIRCULAR_REFERENCE: "DATA_INTEGRITY_CIRCULAR_REFERENCE",
  DATA_INTEGRITY_INVALID_STATE: "DATA_INTEGRITY_INVALID_STATE",

  // Schema validation errors
  SCHEMA_VALIDATION_FAILED: "SCHEMA_VALIDATION_FAILED",
  REQUIRED_FIELD_MISSING: "REQUIRED_FIELD_MISSING",
  INVALID_FORMAT: "INVALID_FORMAT",

  // Import errors
  IMPORT_INVALID_DATE: "IMPORT_INVALID_DATE",
  IMPORT_INVALID_AMOUNT: "IMPORT_INVALID_AMOUNT",
  IMPORT_MISSING_REQUIRED_FIELD: "IMPORT_MISSING_REQUIRED_FIELD",
  IMPORT_CATEGORY_NOT_FOUND: "IMPORT_CATEGORY_NOT_FOUND",
  IMPORT_CHANNEL_NOT_FOUND: "IMPORT_CHANNEL_NOT_FOUND",
  IMPORT_POOL_NOT_FOUND: "IMPORT_POOL_NOT_FOUND",
} as const;
